### PR TITLE
docs: run locally on computer and contributing

### PR DESCRIPTION
**Pull request by rukundob451**

### CODE REVIEW

**Comment by shivarm** [comment]
After open Any PR you don't need to send me. I will check them when I get
home.

Thanks

**Comment by shivarm** [comment]
Thanks for your contribution!

**Comment by rukundob451** [comment]
Alright thank you, I am just trying to get more used to contributing and
getting more familiar with the platform.

**Comment by shivarm** [comment]
@rukundob451  You need to open this PR  again but don't make change in `index.html` file

**Comment by rukundob451** [comment]
Alright, going to do so as required.

Thank you.

**Pull request merged**
